Remove comment from "lambda:DeleteFunction"
In attempt to deploy serverless-nextjs without the use of custom domains, this permission is still required or an error message like this comes up:

AccessDeniedException: User: arn:aws:sts::***:assumed-role/myRole/Role is not authorized to perform: lambda:DeleteFunction