klaw seems to be a dependency for "lambda-at-edge"
When installing `lambda-at-edge` independently and running the example code

```
const path = require('path');
const { Builder } = require("@sls-next/lambda-at-edge");

const nextConfigDir = __dirname;
const outputDir = path.join(nextConfigDir, ".serverless_nextjs");

const builder = new Builder(
  nextConfigDir,
  outputDir,
  {
    cmd: './node_modules/.bin/next',
    cwd: process.cwd(),
    env: {},
    args: ['build']
  }
);

(async () => await builder.build())();
```

I get the following error:

```
 node build.js
node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module 'klaw'
```

Installing `klaw` via npm / yarn fixes it.